### ISSUE TITLE
Rótulo em barras empilhadas

### ISSUE THREAD

**Issue by clebercsm** [academiadocodigo/TBGWebCharts#10]
Ao utilizar `.Charts._ChartType(bar) .Attributes.Labelling` com `.Stacked(True)` os rótulos acabam se sobrepondo, teria como identificar em qual barra seria utilizado o rótulo?

**Comment by alepmedeiros** [comment]
neste caso teria que ser verificado nos exemplos, ou dentro do próprio código navegando neles poderá ter maior acertividade
